### ISSUE TITLE
Problem with .alpha and .omega in mobile.css

### ISSUE THREAD

**Issue by Ybbet** [nathansmith/adapt#23] opened 2012-12-06 11:00 UTC
Hi…

It's hard to explain it… But, when we use mobile.css and we have a grid_x in a grid_x, we have margin-left and margin-right at 10px. But if we have .alpha or .omega, we have margin-left and margin-right at "0"…
OK…

But, for example : 

<pre>
<div class="grid_12">
  <div class="grid_4 alpha">
  </div>

  <div class="grid_4">
  </div>

  <div class="grid_4 omega">
  </div>

</div>
</pre>

(if you don't see above, below the representative code : )
div.grid_12
  div.grid_4.alpha /div
  div.grid_4 /div
  div.grid_4.omega /div
/div.grid_12

So, for grid_4.alpha, we have margin-left and margin-right : "0"
for grid_4, margin-left and margin-right : 10px
grid_4.omega, margin-left and margin-right : "0"
and grid_12 margin-left and margin-right : 10px…

This creates a gap between the different .grid_4 in .grid_12

Do you see the problem ?

A possible solution would be to make margin-left and margin-right of grid_x in a grid_x to "0"…
An other solution : .alpha and .omega will have margin-left and margin-right at 10px…

**Comment by Ybbet** [comment] 2012-12-06 11:02
Oups… https://github.com/nathansmith/adapt/pull/9

**Comment by nathansmith** [comment] 2012-12-06 19:27
Yeah, since I had to reserve some space to ensure nothing touches the edges of a phone's viewport, essentially any `.grid_X` classes will be treated the same, regardless of whether they have `.alpha` or `.omega` classes.

And, since this is a duplicate of number 9, I'm going to close it.

**Closed as completed by nathansmith** 2012-12-06 19:27 UTC
