### ISSUE TITLE
Demo files don't work locally in Chrome

### ISSUE THREAD

**Issue by cpharris** [nathansmith/adapt#22] opened 2012-10-25 04:00 UTC
I'm running Chrome Version 22.0.1229.94 m. The test_class.html and test_id.html don't work properly when viewing the files locally. You have to F5 (refresh) in order for the DIV elements to display. I put the files on a live Apache server and they worked fine on first load. Not sure if this is a Chrome issue or code issue.

**Comment by nathansmith** [comment] 2012-10-25 15:25
I just tried this in Chrome version 22, and it worked fine for me locally.

I'm using a Mac, with OS X Lion. Are you on Windows?

(Just wondering how I can go about reproducing the problem.)

**Comment by cpharris** [comment] 2012-10-25 18:41
Hi Nathan,

I'm running Windows 7 Ultimate. I initially noticed the problem at work where some of the options of Chrome are locked down by IT but I just tried it at home where I have full permissions on Chrome (same version) and the same thing happens.

Also, I misspoke about the DIV elements; It's actually the "Visible at: X by X" P elements that aren't displaying on first load.

**Comment by nathansmith** [comment] 2012-10-25 19:03
Interesting. Perhaps that's a restriction of Chrome on Windows, due to local file access? I'm not sure.

Unfortunately, I don't think there's anything I can do about it. I'm just glad it works in an actual server/page.

**Comment by cpharris** [comment] 2012-10-25 19:14
True. Yea, it's not a big deal since it does work where it's supposed to work (on a web server). Just an FYI for you and anyone else though. I was scratching my head for a little while wondering why it won't work locally.

**Comment by nathansmith** [comment] 2012-10-25 19:22
Gotcha. I'll just close this, but kind of treat it as a "known issue" with Chrome on Windows.

**Closed as completed by nathansmith** 2012-10-25 19:22 UTC
